version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://admin:admin@dev-db:5432/TTM
    depends_on:
      - dev-db

  dev-db:
    image: postgres:13
    container_name: postgres-db
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TTM
    volumes:
      - pgdata:/var/lib/postgresql/data

  prisma-studio:
    image: node:18-alpine
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npx prisma generate && npx prisma studio"
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: postgres://admin:admin@dev-db:5432/TTM
    depends_on:
      - dev-db

volumes:
  pgdata:
